---
root: true
extends:
- plugin:compat/recommended
- plugin:prettier/recommended
- plugin:jest/recommended
- prettier
plugins:
- jest
env:
  browser: true
  jest/globals: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
globals:
  window: readonly
  document: readonly
  Promise: readonly
settings:
  polyfills:
  - Promise
rules:
  constructor-super: error
  dot-notation: error
  eol-last: error
  eqeqeq:
  - error
  - smart
  no-alert: error
  no-bitwise: error
  no-caller: error
  no-console: 'off'
  no-const-assign: error
  no-debugger: warn
  no-dupe-args: error
  no-dupe-class-members: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-duplicate-imports: error
  no-else-return: error
  no-eval: error
  no-extra-semi: error
  no-fallthrough: error
  no-lonely-if: error
  no-mixed-spaces-and-tabs: 'off'
  no-multi-spaces: error
  no-multi-str: 'off'
  no-multiple-empty-lines:
  - warn
  - max: 1
  no-nested-ternary: error
  no-redeclare: error
  no-shadow: warn
  no-undef-init: error
  no-undef: error
  no-unreachable: error
  no-unsafe-negation: error
  no-unused-expressions: warn
  no-unused-vars:
  - warn
  - argsIgnorePattern: "^_"
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-return: error
  no-whitespace-before-property: error
  prefer-const: "off"
  semi: error
  valid-typeof: error
  yoda: warn
