---
bracketSpacing: true
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 120
quoteProps: as-needed
semi: true
singleQuote: false
trailingComma: es5
useTabs: true
arrowParens: always
overrides:
- files:
  - "*.yml"
  - "*.yaml"
  options:
    tabWidth: 2
    useTabs: false
